# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: dea860f9-md-tks
  namespace: dea860f9
spec:
  clusterName: dea860f9
  replicas: 1
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        servicemesh: enabled
        taco-egress-gateway: enabled
        taco-ingress-gateway: enabled
        taco-lma: enabled
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: dea860f9-md-tks
      clusterName: dea860f9
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ByoMachineTemplate
        name: dea860f9-md-tks
      version: v1.22.3
